# Generated by Django 3.1.1 on 2020-09-27 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, verbose_name='City name')),
                ('code', models.CharField(max_length=4, verbose_name='City code')),
            ],
        ),
        migrations.CreateModel(
            name='Directions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fly_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fly_from', to='app.city')),
                ('fly_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fly_to', to='app.city')),
            ],
        ),
    ]
